//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MGPL.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMGPLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MGPLBaseListener : IMGPLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChunk([NotNull] MGPLParser.ChunkContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.chunk"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChunk([NotNull] MGPLParser.ChunkContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] MGPLParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] MGPLParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] MGPLParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] MGPLParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] MGPLParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] MGPLParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.if_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stat([NotNull] MGPLParser.If_statContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.if_stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stat([NotNull] MGPLParser.If_statContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.stat_or_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat_or_block([NotNull] MGPLParser.Stat_or_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.stat_or_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat_or_block([NotNull] MGPLParser.Stat_or_blockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.func_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_dec([NotNull] MGPLParser.Func_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.func_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_dec([NotNull] MGPLParser.Func_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.func_variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_variables([NotNull] MGPLParser.Func_variablesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.func_variables"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_variables([NotNull] MGPLParser.Func_variablesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.func_var_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_var_dec([NotNull] MGPLParser.Func_var_decContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.func_var_dec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_var_dec([NotNull] MGPLParser.Func_var_decContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_body([NotNull] MGPLParser.Func_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.func_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_body([NotNull] MGPLParser.Func_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] MGPLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] MGPLParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.attnamelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttnamelist([NotNull] MGPLParser.AttnamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.attnamelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttnamelist([NotNull] MGPLParser.AttnamelistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttrib([NotNull] MGPLParser.AttribContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.attrib"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttrib([NotNull] MGPLParser.AttribContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.laststat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLaststat([NotNull] MGPLParser.LaststatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.laststat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLaststat([NotNull] MGPLParser.LaststatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] MGPLParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] MGPLParser.LabelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncname([NotNull] MGPLParser.FuncnameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.funcname"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncname([NotNull] MGPLParser.FuncnameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarlist([NotNull] MGPLParser.VarlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.varlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarlist([NotNull] MGPLParser.VarlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamelist([NotNull] MGPLParser.NamelistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.namelist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamelist([NotNull] MGPLParser.NamelistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplist([NotNull] MGPLParser.ExplistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.explist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplist([NotNull] MGPLParser.ExplistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] MGPLParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] MGPLParser.ExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.propertyAccessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyAccessor([NotNull] MGPLParser.PropertyAccessorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.propertyAccessor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyAccessor([NotNull] MGPLParser.PropertyAccessorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrefixexp([NotNull] MGPLParser.PrefixexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.prefixexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrefixexp([NotNull] MGPLParser.PrefixexpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctioncall([NotNull] MGPLParser.FunctioncallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.functioncall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctioncall([NotNull] MGPLParser.FunctioncallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarOrExp([NotNull] MGPLParser.VarOrExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.varOrExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarOrExp([NotNull] MGPLParser.VarOrExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] MGPLParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] MGPLParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarSuffix([NotNull] MGPLParser.VarSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.varSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarSuffix([NotNull] MGPLParser.VarSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNameAndArgs([NotNull] MGPLParser.NameAndArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.nameAndArgs"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNameAndArgs([NotNull] MGPLParser.NameAndArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgs([NotNull] MGPLParser.ArgsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgs([NotNull] MGPLParser.ArgsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctiondef([NotNull] MGPLParser.FunctiondefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.functiondef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctiondef([NotNull] MGPLParser.FunctiondefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncbody([NotNull] MGPLParser.FuncbodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.funcbody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncbody([NotNull] MGPLParser.FuncbodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParlist([NotNull] MGPLParser.ParlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.parlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParlist([NotNull] MGPLParser.ParlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTableconstructor([NotNull] MGPLParser.TableconstructorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.tableconstructor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTableconstructor([NotNull] MGPLParser.TableconstructorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldlist([NotNull] MGPLParser.FieldlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.fieldlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldlist([NotNull] MGPLParser.FieldlistContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] MGPLParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] MGPLParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldsep([NotNull] MGPLParser.FieldsepContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.fieldsep"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldsep([NotNull] MGPLParser.FieldsepContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorOr([NotNull] MGPLParser.OperatorOrContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorOr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorOr([NotNull] MGPLParser.OperatorOrContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAnd([NotNull] MGPLParser.OperatorAndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorAnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAnd([NotNull] MGPLParser.OperatorAndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorComparison([NotNull] MGPLParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorComparison"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorComparison([NotNull] MGPLParser.OperatorComparisonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorStrcat([NotNull] MGPLParser.OperatorStrcatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorStrcat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorStrcat([NotNull] MGPLParser.OperatorStrcatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorAddSub([NotNull] MGPLParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorAddSub"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorAddSub([NotNull] MGPLParser.OperatorAddSubContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorMulDivMod([NotNull] MGPLParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorMulDivMod"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorMulDivMod([NotNull] MGPLParser.OperatorMulDivModContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorBitwise([NotNull] MGPLParser.OperatorBitwiseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorBitwise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorBitwise([NotNull] MGPLParser.OperatorBitwiseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorUnary([NotNull] MGPLParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorUnary"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorUnary([NotNull] MGPLParser.OperatorUnaryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorPower([NotNull] MGPLParser.OperatorPowerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.operatorPower"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorPower([NotNull] MGPLParser.OperatorPowerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] MGPLParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] MGPLParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MGPLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] MGPLParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MGPLParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] MGPLParser.StringContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
